apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-api
  namespace: ehs
spec:
  template:
    spec:
      volumes:
        - name: kafka-ca
          secret:
            secretName: kafka-ca-cert
      containers:
        - name: core-api
          envFrom:
            - secretRef:
                name: kafka-credentials
          volumeMounts:
            - name: kafka-ca
              mountPath: /etc/kafka/ssl
              readOnly: true
