/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a new tenant + admin user */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        user: {
                            /** Format: email */
                            email: string;
                            password: string;
                            name: string;
                            organization_name?: string;
                        };
                    };
                };
            };
            responses: {
                /** @description Created — JWT in Authorization header */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Validation failed (e.g. duplicate email) */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["Problem"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchange credentials for a JWT */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        user: {
                            /** Format: email */
                            email: string;
                            password: string;
                        };
                    };
                };
            };
            responses: {
                /** @description OK — JWT in Authorization header */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Invalid credentials */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["Problem"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke the current JWT */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}/corrective_actions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incident_id: number;
            };
            cookie?: never;
        };
        /** List corrective actions for an incident */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    incident_id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK — actions scoped by Pundit policy */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized — no token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** Create a corrective action for an incident */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    incident_id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        corrective_action: {
                            title: string;
                            description: string;
                            /** Format: date-time */
                            due_date: string;
                            assignee_id: number;
                        };
                    };
                };
            };
            responses: {
                /** @description Created — emits CorrectiveActionAssigned to outbox */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Forbidden — workers cannot create corrective actions */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Validation error (blank title or past due_date) */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["Problem"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/corrective_actions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        /** Get a single corrective action */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found — action belongs to another org */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/corrective_actions/{id}/transitions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run an AASM transition on a corrective action */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        event: "start" | "complete" | "verify" | "cancel";
                    };
                };
            };
            responses: {
                /** @description Transition applied — assignee starts action */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Invalid or unknown event */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["Problem"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List incidents (paginated, Pundit-scoped) */
        get: {
            parameters: {
                query?: {
                    state?: string;
                    severity?: number;
                    site_id?: number;
                    q?: string;
                    page?: number;
                    per_page?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized — no or invalid token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** Create a new (draft) incident */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        incident: {
                            site_id: number;
                            incident_type: string;
                            severity: number;
                            /** Format: date-time */
                            occurred_at: string;
                            location: string;
                            summary: string;
                            description: string;
                        };
                    };
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Validation error */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["Problem"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        /** Get an incident */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found — incident not in caller's Pundit scope */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update an incident */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        incident?: {
                            summary?: string;
                            description?: string;
                            severity?: number;
                        };
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/api/v1/incidents/{id}/transitions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run an AASM state transition */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        event: "submit" | "triage" | "verify" | "close" | "reopen";
                        assignee_id?: number;
                        severity?: number;
                    };
                };
            };
            responses: {
                /** @description Transition applied */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Forbidden — caller authorized to see the incident but not perform this transition */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Invalid transition or unknown event */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["Problem"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description RFC 7807 problem+json error envelope */
        Problem: {
            type?: string;
            title?: string;
            status?: number;
            detail?: string;
            instance?: string;
        };
        UserAttributes: {
            /** Format: email */
            email?: string;
            name?: string;
            /** @enum {string} */
            role?: "worker" | "investigator" | "admin";
            organization_id?: number;
            /** Format: date-time */
            confirmed_at?: string | null;
            /** Format: date-time */
            locked_at?: string | null;
            /** Format: date-time */
            deleted_at?: string | null;
        };
        IncidentAttributes: {
            /** @enum {string} */
            state?: "draft" | "submitted" | "investigating" | "pending_closure" | "closed";
            incident_type?: string;
            severity?: number;
            /** Format: date-time */
            occurred_at?: string;
            location?: string;
            summary?: string;
            description?: string;
            root_cause?: string | null;
            /** Format: date-time */
            submitted_at?: string | null;
            /** Format: date-time */
            triaged_at?: string | null;
            /** Format: date-time */
            closed_at?: string | null;
            site_id?: number;
            reporter_id?: number;
            assignee_id?: number | null;
        };
        CorrectiveActionAttributes: {
            title?: string;
            description?: string;
            /** @enum {string} */
            state?: "open" | "in_progress" | "done" | "verified" | "cancelled";
            /** Format: date-time */
            due_date?: string;
            /** Format: date-time */
            completed_at?: string | null;
            /** Format: date-time */
            verified_at?: string | null;
            overdue?: boolean;
            assignee_id?: number;
            incident_id?: number;
        };
        DashboardAttributes: {
            open_incidents_by_severity?: {
                [key: string]: number;
            };
            incidents_by_state?: {
                [key: string]: number;
            };
            overdue_corrective_actions_count?: number;
            last_30_day_incidents_trend?: {
                /** Format: date */
                date?: string;
                count?: number;
            }[];
            avg_time_to_close_seconds?: number | null;
            sla_compliance?: {
                [key: string]: string;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
